version: '3.7'
services:
    web-server-blog-example:
        build:
            dockerfile: nginx.Dockerfile
            context: ./docker/nginx
        restart: always
        container_name: web-server-blog-example
        ports:
            - '80:80'
        volumes:
            - ./source:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/symfony-cors.conf:/etc/nginx/symfony-cors.conf
        links:
            - php-blog-example
        depends_on:
          - php-blog-example

    php-blog-example:
        container_name: php-blog-example
        build:
            dockerfile: php.Dockerfile
            context: ./docker/php
        ports:
            - '9000:9000'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
          - ./source:/var/www/html
          - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - mysql-blog-example

    mysql-blog-example:
        container_name: mysql-server-blog-example
        image: mysql:5.7
        restart: always
        environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        command:
            - "mysqld"
            - "--local_infile=true"
        ports:
            - "3330:3306"
