<?php

namespace Container8HiHRnG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\CategoryFeature\Application\ApiService\CategoryService' shared autowired service.
     *
     * @return \App\CategoryFeature\Application\ApiService\CategoryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/CategoryFeatureApi/Service/CategoryServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/ApiService/CategoryService.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/DTOResponseMapper/CategoryMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/DTOResponseMapper/CategoryMapper.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/DTOResponseFactory/CategoryFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/DTOResponseFactory/CategoryFactory.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/DTODomainMapper/CategoryMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/DTODomainMapper/CategoryMapper.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Domain/Factory/CategoryFactory.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/Model/CategoryManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/Model/CategoryManager.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Domain/Interactor/CategorySaveInteractor.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Domain/Repository/CategoryRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Infrastructure/Repository/CategoryRepository.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Infrastructure/DataMapper/CategoryDomainMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Infrastructure/DataMapper/CategoryDomainMapper.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Infrastructure/DataMapper/CategoryRequestMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Infrastructure/DataMapper/CategoryRequestMapper.php';
        include_once \dirname(__DIR__, 4).'/src/DataManagerFeatureApi/DTORequestFactory/CategoryDataRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DTORequestFactory/CategoryRequestFactory.php';
        include_once \dirname(__DIR__, 4).'/src/DataManagerFeatureApi/Service/CategoryDataServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/ApiService/CategoryService.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DataMapper/DataMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DataMapper/CategoryMapper.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DTOResponseFactory/CategoryResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DTOResponseFactory/CategoryResponseFactory.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Domain/Interactor/CategoryDeleteInteractor.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Domain/Interactor/CategoryLoadInteractor.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/DTORequestValidator/CategoryValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/CategoryFeature/Application/DTORequestValidator/CategoryValidator.php';

        $a = new \App\CategoryFeature\Domain\Factory\CategoryFactory();
        $b = new \App\CategoryFeature\Infrastructure\Repository\CategoryRepository(new \App\CategoryFeature\Infrastructure\DataMapper\CategoryDomainMapper($a), new \App\CategoryFeature\Infrastructure\DataMapper\CategoryRequestMapper(new \App\DoctrineDataFeature\Application\DTORequestFactory\CategoryRequestFactory()), new \App\DoctrineDataFeature\Application\ApiService\CategoryService(new \App\DoctrineDataFeature\Application\DataMapper\CategoryMapper(new \App\DoctrineDataFeature\Application\DTOResponseFactory\CategoryResponseFactory()), ($container->privates['App\\DoctrineDataFeature\\Infrastructure\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService'))));

        return $container->privates['App\\CategoryFeature\\Application\\ApiService\\CategoryService'] = new \App\CategoryFeature\Application\ApiService\CategoryService(new \App\CategoryFeature\Application\DTOResponseMapper\CategoryMapper(new \App\CategoryFeature\Application\DTOResponseFactory\CategoryFactory()), new \App\CategoryFeature\Application\DTODomainMapper\CategoryMapper($a), new \App\CategoryFeature\Application\Model\CategoryManager(new \App\CategoryFeature\Domain\Interactor\CategorySaveInteractor($b), new \App\CategoryFeature\Domain\Interactor\CategoryDeleteInteractor($b), new \App\CategoryFeature\Domain\Interactor\CategoryLoadInteractor($b, $a)), new \App\CategoryFeature\Application\DTORequestValidator\CategoryValidator(($container->privates['debug.validator'] ?? $container->getDebug_ValidatorService())));
    }
}
