<?php

namespace Container8HiHRnG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\PostFeature\Application\ApiService\PostService' shared autowired service.
     *
     * @return \App\PostFeature\Application\ApiService\PostService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/PostFeatureApi/Service/PostServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/ApiService/PostService.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/Model/PostManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/Model/PostManager.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Domain/Interactor/PostLoadInteractor.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Domain/Factory/PostFactory.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Domain/Repository/PostRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Infrastructure/Repository/PostRepository.php';
        include_once \dirname(__DIR__, 4).'/src/DataManagerFeatureApi/Service/PostDataServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/ApiService/PostService.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DataMapper/DataMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DataMapper/PostMapper.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DTOResponseFactory/PostResponseFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DTOResponseFactory/PostResponseFactory.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Infrastructure/DataMapper/PostDomainMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Infrastructure/DataMapper/PostDomainMapper.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Infrastructure/DataMapper/PostRequestMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Infrastructure/DataMapper/PostRequestMapper.php';
        include_once \dirname(__DIR__, 4).'/src/DataManagerFeatureApi/DTORequestFactory/PostDataRequestFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DoctrineDataFeature/Application/DTORequestFactory/PostRequestFactory.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Domain/Interactor/PostSaveInteractor.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Domain/Interactor/PostDeleteInteractor.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/DTOResponseMapper/PostMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/DTOResponseMapper/PostMapper.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/DTOResponseFactory/PostFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/DTOResponseFactory/PostFactory.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/DTORequestValidator/PostValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/DTORequestValidator/PostValidator.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/DTODomainMapper/PostMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/PostFeature/Application/DTODomainMapper/PostMapper.php';

        $a = new \App\PostFeature\Domain\Factory\PostFactory();
        $b = new \App\PostFeature\Infrastructure\Repository\PostRepository(new \App\DoctrineDataFeature\Application\ApiService\PostService(new \App\DoctrineDataFeature\Application\DataMapper\PostMapper(new \App\DoctrineDataFeature\Application\DTOResponseFactory\PostResponseFactory(), ($container->privates['App\\DoctrineDataFeature\\Infrastructure\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService'))), ($container->privates['App\\DoctrineDataFeature\\Infrastructure\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService'))), new \App\PostFeature\Infrastructure\DataMapper\PostDomainMapper($a), new \App\PostFeature\Infrastructure\DataMapper\PostRequestMapper(new \App\DoctrineDataFeature\Application\DTORequestFactory\PostRequestFactory()));

        return $container->privates['App\\PostFeature\\Application\\ApiService\\PostService'] = new \App\PostFeature\Application\ApiService\PostService(new \App\PostFeature\Application\Model\PostManager(new \App\PostFeature\Domain\Interactor\PostLoadInteractor($a, $b), new \App\PostFeature\Domain\Interactor\PostSaveInteractor($b), new \App\PostFeature\Domain\Interactor\PostDeleteInteractor($b)), new \App\PostFeature\Application\DTOResponseMapper\PostMapper(new \App\PostFeature\Application\DTOResponseFactory\PostFactory()), new \App\PostFeature\Application\DTORequestValidator\PostValidator(($container->privates['debug.validator'] ?? $container->getDebug_ValidatorService())), new \App\PostFeature\Application\DTODomainMapper\PostMapper($a));
    }
}
